name: openclaw
icon: openclaw
title: OpenClaw

services:
- name: openclaw
  title: OpenClaw
  service: openclaw
  required: true

- name: tailscale
  title: Tailscale
  service: tailscale
  required: true
  links:
  - name: serve
    service: openclaw
